### PR TITLE
GH-462: Add exponential backoff to host watcher

### LINKED ISSUE #462: Host watcher continually tries to get records for unreachable host
Priority: Low/Medium/High (choose one, remove the other options)

## Expected Behaviour
* TBD, but shouldn't keep printing log statements and trying continually to lookup the IP

## Actual Behaviour

Host Watcher can fall into a loop of continuously trying to get the IPs for a host that does not resolve:

```
2022-10-11T07:59:45.001Z ERROR kcp-glbc-ingress/glbc.host-watcher runtime/asm_amd64.s:1571 Failed to lookup IP address {"key": "****", "host": "<somehost>", "error": "no records found for host"}
``` 

### Steps to Reproduce the Problem

1. Run local-setup using a CRC cluster (make local-setup USE_CRC=true)
2. Create the echo sample service
3. Stop the crc cluster
4. Look at the logs (Note this will happen for every DNSRecord pointing at that same cluster, so the more there are, the more logs there will be)

## Suggested Resolution
*

## Additional Information

*

### PR DESCRIPTION
**Pull request by sergioifg94**
Closes #462 

## Description of Changes

Implement exponential back off when the host watcher fails to resolve a host

## Release and Testing

1. Run local-setup using a CRC cluster (make local-setup USE_CRC=true)
2. Create the echo sample service
3. Stop the crc cluster
4. Look at the logs (Note this will happen for every DNSRecord pointing at that same cluster, so the more there are, the more logs there will be)
    * The logs will not be so polluted as the host watcher waits before retrying with exponential backoff

## Dependencies

- [ ] Perequisites that must be completed before merging this pull request

### CODE REVIEW

File: pkg/_internal/util/utils.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package util
```
Comment (maleck13) [inline pkg/_internal/util/utils.go:1]: perhaps we could move this to a `numbers` or `math` package rather than util

File: pkg/dns/host_watcher.go [hunk 2]
```diff
@@ -105,9 +111,15 @@ func (w *RecordWatcher) watch(ctx context.Context) {
 			newRecords, err := w.resolver.LookupIPAddr(ctx, w.Host)
 			if err != nil {
 				w.logger.Error(err, "Failed to lookup IP address")
+				sleepTime := w.errInterval
+				w.errInterval = w.errInterval * time.Duration(2)
+				time.Sleep(util.Max(sleepTime, maxErrorInterval))
```
Comment (maleck13) [inline pkg/dns/host_watcher.go:116]: so this is always going to be a default of 5 mins until sleepTime reaches something > than 5 mins? The `maxErrorInterval` is an odd name for it. Maybe I have missed something but it actually seems like the `minErrorInterval`?

Comment (maleck13) [reply pkg/dns/host_watcher.go:116]: Sudo code change below that might improve readability 
`
var minErrorInterval time.Duration = time.Seconds * 30				
time.Sleep(util.Max(w.errInterval, minErrorInterval))
w.errInterval = minErrorInterval * time.Duration(2)
`

**Review by maleck13 — COMMENTED** [review]
left some comments about the impl

File: pkg/dns/host_watcher.go (hunk 2 above)
Comment (sergioifg94) [reply pkg/dns/host_watcher.go:116]: Thanks @maleck13  I made a mistake there. What I should have done was `Min` instead of `Max`, to limit how long the interval is, as it grows exponentially so it wouldn't take to long to become an unrealistically long interval.

Another thing I noticed I have wrong there is that the `errInterval` is not growing exponentially but linearly, it should be calculated to the power of 2, not multiplied by 2

**Comment by sergioifg94** [comment]
Just pushed some changes addressing the issues. So the error interval at the moment grows exponentially starting at 2 seconds: 2, 4, 8, 16... but stops growing once it reaches 5 minutes

Also moved the new utility functions to a `math` package, and added some unit tests for them

**Review by maleck13 — APPROVED** [review]
